export const THEME_COLOR = {
  light: {
    body: '#e7eff4',
    fontColor: '#31c193',
    linkFontColor: '#27ae60',
    activeBgColor: '#f1f3f5',
    listBgColor: '#fff',
    leftBarBgColor: '#fff',
    rightTitleBgColor: '#fff',
    rightLinkItemBgColor: 'rgba(255,255,255,0.8)',
    inputColor: '#ffffff',
    inputBgColor: 'rgba(52, 73, 94, 0.5)',
  },
  dark: {
    body: '#434343',
    fontColor: '#fff',
    listBgColor: '#434343',
    activeBgColor: '#868e96',
    linkFontColor: '#FFFFE0',
    leftBarBgColor: '#242424',
    rightTitleBgColor: '#242424',
    rightLinkItemBgColor: 'rgba(36,36,36,0.8)',
    inputColor: '#ecf0f1',
    inputBgColor: '#2f3542',
  },
}

export const HOVER_CLASS = [
  'hvr-sweep-to-right',
  'hvr-sweep-to-left',
  'hvr-sweep-to-bottom',
  'hvr-sweep-to-bottom',
  'hvr-bounce-to-right',
  'hvr-bounce-to-left',
  'hvr-bounce-to-bottom',
  'hvr-bounce-to-top',
  'hvr-radial-out',
  'hvr-rectangle-out',
  'hvr-shutter-out-vertical',
]
